FROM node:13.11-alpine AS builder
LABEL MAINTAINER="Jonathan Villanueva frik_ej2v@hotmail.com"
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --silent
ENV PATH="./node_modules/.bin:$PATH"
COPY . ./
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html

COPY ./nginx/app.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]