# pull official base image
FROM node:13.11-alpine


ARG GOOGLE_CLIENT_ID=default
ENV GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

# add app
COPY . ./

EXPOSE 3000

# start app
CMD ["npm", "start"]